---
# tasks file for install-docker
- name: install dependency
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: policy docker-ce
  shell: apt-cache policy docker-ce

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: restart docker
  command: echo "this task will restart the docker services"
  notify: "restart docker"

- name: Make sure docker is active
  service:
    name: docker
    state: started
    enabled: yes
